### PR TITLE
updated libtremor git repo

### PR DESCRIPTION
**Pull request by Bhaal22**
#5 https://gitlab.xiph.org/xiph/tremor.git is the new git repo

### CODE REVIEW

**Comment by ljsebald** [comment]
We were using the lowmem branch before... Can you update the PR to pull that instead of master? I'll be happy to merge it then.

**Comment by andressbarajas** [comment]
No need for the KOSMakefile.mk changes @Bhaal22. You can undo that and then change master => lowmem

**Comment by Bhaal22** [comment]
cool wil lupdate PR then!

**Comment by Bhaal22** [comment]
PR is updated. only one file changed

**Pull request merged**
